---

#
# INSTALL JENKINS WITH DOCKER
#
#
# INFORMATIONS
#
# Maintainer: AJC-GR4
# Version: 1
# Release date: 05-17-2021
#
#
# WARNING
#
# 1. At least 4 Gio of RAM is required
#    Consequently, if you are using Azure VM, the size must be 'Standard_B2ms' or higher
#
#
# NOTE
#
# 1. Edit ./vars/vars.yml to set your own parameters
#


- name: INSTALL CI-SRV WITH DOCKER-COMPOSE
  hosts: azure-gitlab
  remote_user: "{{ admin_user_name }}"
  become: yes
  #become_method: su
  #become_user: root



  vars_files:
    - ./vars/vars.yml


  tasks:

    - name: Create Gitlab environment
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ admin_user_name }}"
        group: "{{ admin_user_name }}"
        mode: 0775
      with_items:
        - "/home/{{ admin_user_name }}/gitlab"
        - "/home/{{ admin_user_name }}/gitlab/config"
        - "/home/{{ admin_user_name }}/gitlab/log"
        - "/home/{{ admin_user_name }}/gitlab/data"

    - name: Create jenkins directory on docker host
      file:
        state: directory
        owner: 1000
        group: 1000
        path: "/home/{{ admin_user_name }}/jenkins-data"

    - name: Set docker-compose file from template
      template:
        src: ./templates/docker-compose.docker-ci-srv.j2
        dest: "{{ docker_compose_path }}/{{ docker_compose_file }}"
        mode: '0700'

    - name: Start containers using shell command
      command: "docker-compose -f {{ docker_compose_file }} up -d"
      args:
        chdir: "{{ docker_compose_path }}"

...
