---

- name: AZURE - Public IP address creation - myPublicIP-lamp-ha
  azure_rm_publicipaddress:
    resource_group: GrpeRessGrp4
    allocation_method: Static
    name: myPublicIP-lamp-ha
  register: output_ip_address

- name: AZURE-INFO - Dump public IP for VM which will be created
  debug:
    msg: "Adresse IP publique (lamp-ha): {{ output_ip_address.state.ip_address }}"

- name: AZURE - Virtual network interface card creation - myNIC-lamp-ha
  azure_rm_networkinterface:
    resource_group: GrpeRessGrp4
    name: myNIC-lamp-ha
    virtual_network: myNetwork
    subnet: mySubnet
    public_ip_name: myPublicIP-lamp-ha
    security_group: myNetworkSG-linux

- name: AZURE - VM creation - LAMPHAGrp4
  azure_rm_virtualmachine:
    resource_group: GrpeRessGrp4
    name: LAMPHAGrp4
    vm_size: Standard_DS1_v2
    admin_username: gui
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/gui/.ssh/authorized_keys
        key_data: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"
    network_interfaces: myNIC-lamp-ha
    image:
      offer: debian-10
      publisher: Debian
      sku: '10'
      version: latest

...
