---

#
# INITIAL DEPLOYMENT OF THE PYTHON HTTP SERVER
#
#
# INFORMATIONS
#
# Maintainer:     AJC-GR4
# Version:        1
# Release date:   05-18-2021
#
#
# NOTE
#
# 1. Do not forget to configure the ../hosts file
# 2. Add your settings in the ./vars/vars.yml file
#


- name: INITIAL DEPLOYMENT OF THE PYHTTP APPLICATION
  hosts: azure-pyhttp
  gather_facts: yes
  remote_user: "{{ admin_user_name }}"
  become: yes

  # --- Uncomment the following if the remote hosts do not have sudo
  #     In this case, add '--ask-become-pass' when running the playbook ---
  #become_method: su
  #become_user: root
  

  vars_files:
    - vars/vars.yml


  tasks:

    - name: Install pip
      apt:
        name: python-pip
        state: present
        update_cache: yes

    - name: Install docker-py
      pip:
        name: docker

    - name: Create build directory
      file:
        path: /root/build-docker
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy dockerfile
      copy:
        src: ./build-image/Dockerfile
        dest: /root/build-docker/Dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: Copy pyapp directory
      copy:
        src: ./build-image/pyapp
        dest: /root/build-docker
        owner: root
        group: root
        mode: '0644'
        directory_mode: yes

    - name: Build docker image
      command: docker build -t pyhttp .
      args:
        chdir: /root/build-docker

    - name: Run pyhttp container
      command: docker run -d -p 443:443 pyhttp
      args:
        chdir: /root/build-docker

...
