---
# tasks file for apache_mw
- name: apache installation
  apt:
    name: apache2
    state: latest

- name: apache service activation
  service:
    name: apache2
    state: started
    enabled: yes

# Installation openssl
- name: install openssl
  apt:
    name: openssl
    state: present

# Certificat
- name: certificat request
  command: openssl req -x509 -nodes -days 500 -newkey rsa:2048 -sha256 -out /etc/apache2/server.crt -keyout /etc/apache2/server.key -subj "/C=FR/ST=Savoie/L=Chambery/O=AJC/OU=IT/CN=ajc-mediawiki.com"

- file:
    path: /etc/apache2/server.crt
    mode: 0440

# Activation module SSL
- name: activation SSL apache2
  command: a2enmod ssl

#configuration site mediawiki
- name: Config mediawiki virtualhost
  template:
          src: /home/groupe4/git_labo/ajc_project_v1_0/install-mediawiki/roles/apache_mw/templates/mediawiki-ssl.conf.j2
          dest: /etc/apache2/sites-available/default-ssl.conf


