---
# tasks file for db_mw
# Installation
- name: mariadb-server installation
  apt:
    name:  mariadb-server,python-pymysql
    state: latest

# Starting
- name: start mariadb service
  service:
    name:  mariadb
    state: started
    enabled: yes

# Configuration users
- name: MYSQL - Set root password
  copy:
    dest: "/root/.my.cnf"
    content:
      '[client]
      user=root
      password=123'
  notify: restart mysql

- name: Supprimer anonymous accounts
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: ''
    host_all: yes
    state: absent
  notify: restart mysql

- name: Enlever db test
  mysql_db:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: test
    state: absent
  notify: restart mysql

- name: MYSQL - Create new all granted user
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "gui"
    password: "123"
    priv: '*.*:ALL'
    host: "%"
    state: present
  notify: restart mysql
